name: Echidna Plugins

on:
  push:
    branches:
      - master
      - staged
  pull_request:
    branches:
      - master

jobs:
  UnitAsserts:
    strategy:
      matrix:
        testName:
          - AdaptiveFeeEchidnaTest
          - DataStorageEchidnaTest

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'

      - name: Install dependencies
        run: npm run ci-install

      - name: Compile contracts
        run: npm run compile
        working-directory: ./src/plugins

      - name: Run ${{ matrix.testName }}
        uses: crytic/echidna-action@v2
        with:
          solc-version: 0.8.20
          files: ./src/plugins/
          contract: ${{ matrix.testName }}
          crytic-args: --hardhat-ignore-compile
          solc-args: --evm-version paris
          config: ./src/plugins/contracts/test/echidna/echidna.config.yml

