name: Tests

on:
  push:
    branches:
      - master
      - staged
  pull_request:
    branches:
      - master

jobs:
  Core:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'
          cache-dependency-path: package-lock.json
      - run: npm run ci-install
      - run: npm run compile
        working-directory: ./src/core
      - run: npm run test
        working-directory: ./src/core


  Periphery:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./src/periphery

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'
          cache-dependency-path: package-lock.json
      - run: npm run bootstrap
        working-directory: ./
      - run: npm run compile
      - run: npm run test
  
  Farming:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./src/tokenomics

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'
          cache-dependency-path: package-lock.json
      - run: npm run bootstrap
        working-directory: ./
      - run: npm run compile
      - run: npm run test
